"""
Core CLI commands for Primus OS
"""

import typer
import requests
from pathlib import Path
from typing import Optional

from core.agents import TaskAnalyzerAgent, AutomationBuilderAgent
from core.tasks import TaskScanner, WorkflowAnalyzer
from config.settings import Settings

app = typer.Typer(help="Primus OS - AI-Powered Manual Task Automation")

@app.command()
def scan(
    target: str = typer.Argument(..., help="Path or URL to scan for manual tasks"),
    output: Optional[Path] = typer.Option(None, help="Output file for scan results"),
    verbose: bool = typer.Option(False, help="Enable verbose output")
):
    """
    Scan a system, workflow, or documentation for manual tasks that can be automated.
    """
    typer.echo(f"🔍 Scanning {target} for manual tasks...")

    scanner = TaskScanner()
    tasks = scanner.scan(target)

    if verbose:
        typer.echo(f"Found {len(tasks)} potential manual tasks:")
        for task in tasks:
            typer.echo(f"  - {task}")

    if output:
        # Save results to file
        with open(output, 'w') as f:
            f.write(f"Manual Tasks Found in {target}:\n")
            for task in tasks:
                f.write(f"- {task}\n")
        typer.echo(f"✅ Results saved to {output}")

@app.command()
def analyze(
    input_file: Path = typer.Argument(..., help="File containing task descriptions"),
    model: str = typer.Option("gpt-4", help="AI model to use for analysis")
):
    """
    Analyze manual tasks and generate automation recommendations.
    """
    typer.echo(f"🧠 Analyzing tasks from {input_file} using {model}...")

    analyzer = WorkflowAnalyzer()
    recommendations = analyzer.analyze_file(input_file)

    typer.echo("📋 Automation Recommendations:")
    for rec in recommendations:
        typer.echo(f"  • {rec}")

@app.command()
def build(
    task_description: str = typer.Argument(..., help="Description of the task to automate"),
    output_dir: Path = typer.Option(Path("./automations"), help="Output directory for generated code")
):
    """
    Build automation code for a specific manual task.
    """
    typer.echo(f"🔨 Building automation for: {task_description}")

    builder = AutomationBuilderAgent()
    code = builder.generate_automation(task_description)

    output_dir.mkdir(exist_ok=True)
    output_file = output_dir / "automation.py"

    with open(output_file, 'w') as f:
        f.write(code)

    typer.echo(f"✅ Automation code generated: {output_file}")

@app.command()
def init(
    project_name: str = typer.Argument(..., help="Name of the automation project"),
    template: str = typer.Option("basic", help="Project template to use")
):
    """
    Initialize a new Primus OS automation project.
    """
    typer.echo(f"🚀 Initializing project: {project_name}")

    # Create project structure
    project_dir = Path(project_name)
    project_dir.mkdir(exist_ok=True)

    # Create basic files
    (project_dir / "requirements.txt").write_text("primus-os\n")
    (project_dir / "README.md").write_text(f"# {project_name}\n\nGenerated by Primus OS\n")

    typer.echo(f"✅ Project initialized in {project_dir}")

@app.command()
def dashboard(
    api_url: str = typer.Option("https://your-soloscale-domain.com", help="SoloScale API base URL"),
    api_key: str = typer.Option(..., help="API key for authentication", envvar="SOLOSCALE_API_KEY")
):
    """
    CEO Dashboard: View live revenue, leads, and system health from SoloScale.
    """
    typer.echo("🏛️ SoloScale CEO Dashboard")
    typer.echo("=" * 50)
    
    headers = {"Authorization": f"Bearer {api_key}"} if api_key else {}
    
    try:
        # System Health
        health_response = requests.get(f"{api_url}/api/system/health-metrics", headers=headers)
        if health_response.status_code == 200:
            health = health_response.json()
            typer.echo(f"🟢 System Health: {health.get('status', 'Unknown')}")
            typer.echo(f"📊 Total Leads: {health.get('totalLeads', 0)}")
            typer.echo(f"💰 Revenue: ${health.get('totalRevenue', 0):,.2f}")
            typer.echo(f"🤖 AI Extractions: {health.get('aiExtractions', 0)}")
        else:
            typer.echo(f"❌ Health Check Failed: {health_response.status_code}")
        
        # Recent Leads
        leads_response = requests.get(f"{api_url}/api/leads/recent", headers=headers)
        if leads_response.status_code == 200:
            leads = leads_response.json()
            typer.echo(f"\n📋 Recent Leads ({len(leads)}):")
            for lead in leads[:5]:  # Show top 5
                typer.echo(f"  • {lead['name']} - {lead['status']} (${lead.get('value', 0):,.0f})")
        
        # Performance Metrics
        perf_response = requests.get(f"{api_url}/api/partners/performance", headers=headers)
        if perf_response.status_code == 200:
            perf = perf_response.json()
            typer.echo(f"\n⚡ Performance (Last 7 Days):")
            typer.echo(f"  • Avg Response Time: {perf.get('avgResponseTime', 0)}min")
            typer.echo(f"  • Conversion Rate: {perf.get('conversionRate', 0):.1%}")
            typer.echo(f"  • Active Brokers: {perf.get('activeBrokers', 0)}")
        
    except Exception as e:
        typer.echo(f"❌ Dashboard Error: {str(e)}")
    
    typer.echo("\n💡 Tip: Run 'primus dashboard --help' for options")

if __name__ == "__main__":
    app()