"""
Core CLI commands for Primus OS
"""

import typer
from pathlib import Path
from typing import Optional

from core.agents import TaskAnalyzerAgent, AutomationBuilderAgent
from core.tasks import TaskScanner, WorkflowAnalyzer
from config.settings import Settings

app = typer.Typer(help="Primus OS - AI-Powered Manual Task Automation")

@app.command()
def scan(
    target: str = typer.Argument(..., help="Path or URL to scan for manual tasks"),
    output: Optional[Path] = typer.Option(None, help="Output file for scan results"),
    verbose: bool = typer.Option(False, help="Enable verbose output")
):
    """
    Scan a system, workflow, or documentation for manual tasks that can be automated.
    """
    typer.echo(f"🔍 Scanning {target} for manual tasks...")

    scanner = TaskScanner()
    tasks = scanner.scan(target)

    if verbose:
        typer.echo(f"Found {len(tasks)} potential manual tasks:")
        for task in tasks:
            typer.echo(f"  - {task}")

    if output:
        # Save results to file
        with open(output, 'w') as f:
            f.write(f"Manual Tasks Found in {target}:\n")
            for task in tasks:
                f.write(f"- {task}\n")
        typer.echo(f"✅ Results saved to {output}")

@app.command()
def analyze(
    input_file: Path = typer.Argument(..., help="File containing task descriptions"),
    model: str = typer.Option("gpt-4", help="AI model to use for analysis")
):
    """
    Analyze manual tasks and generate automation recommendations.
    """
    typer.echo(f"🧠 Analyzing tasks from {input_file} using {model}...")

    analyzer = WorkflowAnalyzer()
    recommendations = analyzer.analyze_file(input_file)

    typer.echo("📋 Automation Recommendations:")
    for rec in recommendations:
        typer.echo(f"  • {rec}")

@app.command()
def build(
    task_description: str = typer.Argument(..., help="Description of the task to automate"),
    output_dir: Path = typer.Option(Path("./automations"), help="Output directory for generated code")
):
    """
    Build automation code for a specific manual task.
    """
    typer.echo(f"🔨 Building automation for: {task_description}")

    builder = AutomationBuilderAgent()
    code = builder.generate_automation(task_description)

    output_dir.mkdir(exist_ok=True)
    output_file = output_dir / "automation.py"

    with open(output_file, 'w') as f:
        f.write(code)

    typer.echo(f"✅ Automation code generated: {output_file}")

@app.command()
def init(
    project_name: str = typer.Argument(..., help="Name of the automation project"),
    template: str = typer.Option("basic", help="Project template to use")
):
    """
    Initialize a new Primus OS automation project.
    """
    typer.echo(f"🚀 Initializing project: {project_name}")

    # Create project structure
    project_dir = Path(project_name)
    project_dir.mkdir(exist_ok=True)

    # Create basic files
    (project_dir / "requirements.txt").write_text("primus-os\n")
    (project_dir / "README.md").write_text(f"# {project_name}\n\nGenerated by Primus OS\n")

    typer.echo(f"✅ Project initialized in {project_dir}")

if __name__ == "__main__":
    app()